server:
  port: 7999
spring:
  shardingsphere:
    masterslave:
      name: ds-ms
      slave-data-source-names: ds-slave-0,ds-slave-1
      load-balance-algorithm-type: round_robin
      master-data-source-name: ds-master
    datasource:
      names: ds-master,ds-slave-0,ds-slave-1
      ds-slave-1:
        driver-class-name: com.mysql.jdbc.Driver
        type: com.zaxxer.hikari.HikariDataSource
        username: root
        password: root
        jdbc-url: jdbc:mysql://localhost:3306/slave1?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
      ds-slave-0:
        jdbc-url: jdbc:mysql://localhost:3306/slave0?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
        driver-class-name: com.mysql.jdbc.Driver
        password: root
        username: root
        type: com.zaxxer.hikari.HikariDataSource
      ds-master:
        username: root
        type: com.zaxxer.hikari.HikariDataSource
        password: root
        driver-class-name: com.mysql.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/master?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF-8
  application:
    name: application
  redis:
    redisson:
      config: classpath:redisson.yml
logging:
  level:
    root: info
    com.practice.arch.common.repository: debug
    org.springframework.cache: trace

mybatis:
  mapper-locations: classpath:mapper/*.xml

management:
  endpoints:
    web:
      exposure:
        include: "*"
