server:
  port: 7999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/arch?characterEncoding=utf8
    username: root
    password: abcd123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: application
logging:
  level:
    root: info
    com.practice.arch.common.repository: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml