server:
  port: 7999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/arch?characterEncoding=utf8
    username: root
    password: abcd123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: application
  redis:
    host: localhost
    port: 6379
    timeout: 1000
    database: 0
    #spring.redis.lettuce.pool.max-active=8
    #spring.redis.lettuce.pool.max-idle=8
    #spring.redis.lettuce.pool.max-wait=-1ms
    #spring.redis.lettuce.pool.min-idle=0
    #spring.redis.sentinel.master= # Name of Redis server.
    #spring.redis.sentinel.nodes= # Comma-separated list of host:port pairs.
    #spring.redis.timeout=100ms
logging:
  level:
    root: info
    com.practice.arch.common.repository: debug
mybatis:
  mapper-locations: classpath:mapper/*.xml
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true