package com.practice.arch.generator.domain;

import java.io.Serializable;

public class AmRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AM_ROLE.id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AM_ROLE.name
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AM_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AM_ROLE.id
     *
     * @return the value of AM_ROLE.id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AM_ROLE.id
     *
     * @param id the value for AM_ROLE.id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AM_ROLE.name
     *
     * @return the value of AM_ROLE.name
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AM_ROLE.name
     *
     * @param name the value for AM_ROLE.name
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}