package com.practice.arch.generator.domain;

import java.io.Serializable;

public class AmUserRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AM_USER_ROLE.id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AM_USER_ROLE.user_id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AM_USER_ROLE.role_id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    private Integer roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AM_USER_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AM_USER_ROLE.id
     *
     * @return the value of AM_USER_ROLE.id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AM_USER_ROLE.id
     *
     * @param id the value for AM_USER_ROLE.id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AM_USER_ROLE.user_id
     *
     * @return the value of AM_USER_ROLE.user_id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AM_USER_ROLE.user_id
     *
     * @param userId the value for AM_USER_ROLE.user_id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AM_USER_ROLE.role_id
     *
     * @return the value of AM_USER_ROLE.role_id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public Integer getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AM_USER_ROLE.role_id
     *
     * @param roleId the value for AM_USER_ROLE.role_id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public void setRoleId(Integer roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", userId=").append(userId);
        sb.append(", roleId=").append(roleId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}