package com.practice.arch.generator.domain;

import java.io.Serializable;

public class AmUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AM_USER.id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AM_USER.email
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AM_USER.password
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table AM_USER
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AM_USER.id
     *
     * @return the value of AM_USER.id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AM_USER.id
     *
     * @param id the value for AM_USER.id
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AM_USER.email
     *
     * @return the value of AM_USER.email
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AM_USER.email
     *
     * @param email the value for AM_USER.email
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AM_USER.password
     *
     * @return the value of AM_USER.password
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AM_USER.password
     *
     * @param password the value for AM_USER.password
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", email=").append(email);
        sb.append(", password=").append(password);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}