package com.practice.arch.generator.mapper;

import com.practice.arch.generator.domain.AmRole;
import com.practice.arch.generator.domain.AmRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AmRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    long countByExample(AmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int deleteByExample(AmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int insert(AmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int insertSelective(AmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    List<AmRole> selectByExample(AmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    AmRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") AmRole record, @Param("example") AmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int updateByExample(@Param("record") AmRole record, @Param("example") AmRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int updateByPrimaryKeySelective(AmRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int updateByPrimaryKey(AmRole record);
}