package com.practice.arch.generator.mapper;

import com.practice.arch.generator.domain.AmUser;
import com.practice.arch.generator.domain.AmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AmUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    long countByExample(AmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int deleteByExample(AmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int insert(AmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int insertSelective(AmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    List<AmUser> selectByExample(AmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    AmUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") AmUser record, @Param("example") AmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int updateByExample(@Param("record") AmUser record, @Param("example") AmUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int updateByPrimaryKeySelective(AmUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int updateByPrimaryKey(AmUser record);
}