package com.practice.arch.generator.mapper;

import com.practice.arch.generator.domain.AmUserRole;
import com.practice.arch.generator.domain.AmUserRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AmUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    long countByExample(AmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int deleteByExample(AmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int insert(AmUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int insertSelective(AmUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    List<AmUserRole> selectByExample(AmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    AmUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") AmUserRole record, @Param("example") AmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int updateByExample(@Param("record") AmUserRole record, @Param("example") AmUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int updateByPrimaryKeySelective(AmUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table AM_USER_ROLE
     *
     * @mbg.generated Fri May 22 01:33:42 CST 2020
     */
    int updateByPrimaryKey(AmUserRole record);
}